### ISSUE TITLE
bibtex entry retrieval from dx.doi.org not working

### ISSUE THREAD

**Issue by kjschmid** [jkitchin/org-ref#179] opened 2016-04-09 13:18 UTC
Hi,

I installed the most recent version of org-ref from melpa (`org-ref-20160408.552`) and now try to add some references to the bib file exactly as shown in the youtube video.

Selecting a paper title and using `crossref-add-bibtex-entry` to find it on crossref works fine. Then, I select the correct paper (via helm) and org-ref starts to look it up on dx.doi.org (`Contacting host: dx.doi.org:80`). After a short while, I get the error message:
`Wrong type argument: integer-or-marker-p,nil`

In my Firefox browser (on 2 computers and 2 different networks) all queries to dx.doi.org work only with `https://dx.doi.org` but not with `http://dx.doi.org`. For this reason, I used grep to replace all references in the org-ref .el files from http to `https://dx.doi.org`. org-ref then uses the TLS connection, but as a result, I get a JSON error.

I have tried all of this on a fairly recent emacs: ﻿﻿GNU Emacs 25.0.92.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1603)) of 2016-03-02
with org version 8.3.4 20160404 from  elpa

What could be the problem here?

**Comment by jkitchin** [comment] 2016-04-18 15:57
I am not sure. I can't reproduce this issue. Is it still an issue?

**Comment by kjschmid** [comment] 2016-04-20 03:21
Unfortunately, still an issue, but it seems have to do something with the requirement (on my computers and in my networks) to having access dx.doi.org via https and not http.
So likely not directly related to org-ref.

**Comment by jkitchin** [comment] 2016-04-20 13:35
I have some intermittent issues using https. Sometimes it works, and
sometimes it doesn't. I don't think this is an org-ref issue, but one in
emacs. It seems that this variable url-http-end-of-headers is not always
set correctly and sometimes is nil which causes the problem you see. I
don't know what to do about it. It is odd. it works for a while and doesn't
work for a while.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jagrg** [comment] 2016-04-20 22:51
Both ways worked fine for me :)

**Comment by jkitchin** [comment] 2016-04-20 23:00
Sometimes they both work for me too!;)

On Wednesday, April 20, 2016, Jonathan Gregory <notifications@github.com>
wrote:

> Both ways worked fine for me :)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/179#issuecomment-212643501>
>


-- 
John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by kjschmid** [comment] 2016-04-21 07:53
With the most recent update of org-ref it works for me too on both Mac and Linux machines. Thanks!

**Comment by jkitchin** [comment] 2016-04-21 12:43
ok! I am going to close this.

**Closed by jkitchin** 2016-04-21 12:43 UTC
