### ISSUE TITLE
cite link on first line of org document will not work

### ISSUE THREAD

**Issue by xcapaldi** [jkitchin/org-ref#778] opened 2020-08-18 14:23 UTC
This isn't really a big issue since it probably falls outside the use case for most people.
If you have a cite link as the first line of your org document, the link will not function.
Simply adding a line return before the link solves the issue.

This doesn't work:
```
cite:brochard-1986-polym-polym-inter

bibliography:~/Dropbox/library/references.bib
```

And this does:
```

cite:brochard-1986-polym-polym-inter

bibliography:~/Dropbox/library/references.bib
```

**Comment by fleimgruber** [comment] 2021-01-01 09:51
@xcapaldi I can't reproduce this with latest org-ref from MELPA (org-ref-20201231.1406). Is this still happening for you?

**Comment by jkitchin** [comment] 2021-01-01 19:58
I think this is fixed now. Closing it.

**Closed by jkitchin** 2021-01-01 19:58 UTC

**Comment by xcapaldi** [comment] 2021-01-01 22:15
> @xcapaldi I can't reproduce this with latest org-ref from MELPA (org-ref-20201231.1406). Is this still happening for you?

I just checked this again and it seems to work fine now. Thank you for the follow-up.
