### ISSUE TITLE
org-ref-make-org-link-cite-key-visible and org-table-edit-field: bug?

### ISSUE THREAD

**Issue by olssol** [jkitchin/org-ref#224] opened 2016-05-19 21:05 UTC
When org-table-edit-field was called, the following error occurred:

org-ref-make-org-link-cite-key-visible: Args out of range: #<buffer *Org Table Edit Field*>, 0, 4

Is this a bug in org-table or org-ref? 

Please advise.

**Comment by jkitchin** [comment] 2016-05-19 21:36
hm. I can't reproduce that. what versions of everything do you use?

**Comment by olssol** [comment] 2016-05-19 22:05
Thanks for the prompt reply. 
Is there a way to provide you the details of my setting?

**Comment by jkitchin** [comment] 2016-05-19 23:20
M-x org-ref-debug

usually provides a fair bit of information.

olssol writes:

> Thanks for the prompt reply.
> Is there a way to provide you the details of my setting?
>
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/224#issuecomment-220465536


--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by olssol** [comment] 2016-05-20 03:22
Here you are. Thanks again.

org-ref: Version 0.8.1 (git-commit c115a662105bc8c79382e3a71afea028b8b44a7a)

* Variables
1. org-ref-bibliography-notes: ~/PAPERS.org (exists nil)
2. org-ref-default-bibliography: (~/PAPERS.bib) (exists (t)) (listp t)
3. org-ref-pdf-directory: ~/Papers/ (exists t)

* System
system-type: System: darwin
system-configuration: x86_64-apple-darwin13.4.0
window system: Window system: ns
Emacs: GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)
 of 2015-04-10 on builder10-9.porkrind.org
org-version: 8.3.4

* about org-ref
org-ref installed in /.emacs.d/elpa/org-ref-20160427.1327/org-ref.elc.

** Dependencies
helm-bibtex /.emacs.d/elpa/helm-bibtex-20160422.1600/helm-bibtex.elc

* org-ref-pdf (loaded: nil)
system pdftotext: org-ref-pdf not loaded
You set pdftotext-executable to org-ref-pdf not loaded (exists: org-ref-pdf not loaded)

* org-ref-url-utils (loaded: nil)

* export variables
org-latex-pdf-process:
("xelatex -interaction nonstopmode %f" "bibtex %b" "xelatex -interaction nonstopmode %f" "xelatex -interaction nonstopmode %f")

**Comment by jagrg** [comment] 2016-05-20 13:57
@olssol I was having a similar issue with gnus. Can you evaluate the code below and try again?

```elisp
(defun org-ref-make-org-link-cite-key-visible (&rest _)
  "Make the org-ref cite link visible in descriptive links."
  (unless (string= (buffer-name) "*Org Agenda*")
    (when (and (re-search-forward org-bracket-link-regexp nil t)
    	       (not (org-in-src-block-p)))
    (save-match-data
      (let ((s (match-string 1))
	    (s-begin (match-beginning 1))
	    (s-end (match-end 1))
	    (beg (match-beginning 0))
	    (end (match-end 0))
	    (cite-re (format "^\\(%s:\\)"
			     (regexp-opt (-sort
					  (lambda (a b)
					    (> (length a) (length b)))
					  org-ref-cite-types))))
	    cite-type)

	(when (and s (string-match cite-re s))
	  (setq cite-type (match-string 1 s))
	  (remove-text-properties beg end
				  '(invisible))
	  (add-text-properties
	   beg end
	   `(face (:foreground ,org-ref-cite-color)))))))))
```

**Comment by olssol** [comment] 2016-05-20 14:13
The code works! Thanks @jagrg.

**Comment by jagrg** [comment] 2016-05-20 16:54
Actually instead of:

```
(when (and (re-search-forward org-bracket-link-regexp nil t)
	   (not (org-in-src-block-p)))
```

we need:
```
(when (string-match-p "\\.org$" (buffer-name))
```

**Comment by olssol** [comment] 2016-05-20 17:34
Thanks. The modification works.

**Comment by jkitchin** [comment] 2016-05-24 18:12
Could you submit this fix as a pull request?

**Comment by olssol** [comment] 2016-05-24 18:36
I will more than happy to do it. Would you please provide some more guidance about how to do it as a pull request?

**Comment by jkitchin** [comment] 2016-05-27 19:08
I think this got fixed by @jagrg already. Is that right?

**Comment by jagrg** [comment] 2016-05-27 19:18
Should be fixed yes.

>>>>> On 27 May 2016 at 20:08, John Kitchin <notifications@github.com> wrote:

> I think this got fixed by @jagrg already. Is that right?

> --- You are receiving this because you were mentioned. Reply to this
> email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/224#issuecomment-222229564

-- 
Jonathan

**Closed** 2016-05-29 23:38 UTC
