### ISSUE TITLE
I can't execute actions from the actions menu

### ISSUE THREAD

**Issue by ecijalex** [jkitchin/org-ref#930] opened 2021-11-04 11:57 UTC
I recently upgraded to org-ref 3. References are recognized (pop-up text appears upon hovering the mouse) but when I open the action menu over a reference (C-c C-o), and press a selection (e.g. open pdf) the following message shows up:

`org-ref-get-bibtex-key-under-cursor: Invalid function: (key (get-text-property (point) (quote cite-key)))`

I am not sure how to get around this, maybe some bad configuration or broken update from my setup?

Furthermore, these are my version details
- emacs-version = GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2020-09-19
- org-version = 9.4.6
- org-ref: Version 3.0

**Comment by jkitchin** [comment] 2021-11-04 20:31
I don't know what the cause of that would be. Locally I can't reproduce it. I added a test in the commit above that passes locally. I will see in a bit if it could be related to compiling or something. That line of code uses if-let, which should be ok for Emacs 27 I think.

**Comment by ecijalex** [comment] 2021-11-05 12:51
I've just upgraded to the latest version of org-ref (20211104.1135) and now it works fine. Interestingly I updated it in another machine (along with several emacs packages) and got the same error.  So I will try to reinstall there...

**Comment by jkitchin** [comment] 2021-11-05 12:57
If you find a machine it does not work on, see if `if-let` is a defined macro. It should be autoloaded from `subr-x`. Maybe this another eval-and-compile issue.

**Comment by ecijalex** [comment] 2021-11-06 19:00
In checked if  `if-let` was defined (via scratch buffer) and apparently it was. I carried out the upgrade in the remaining machines and now it works everywhere. I was wondering if it could be related to the fact that usually I have org files open with org-ref activated when I upgrade -I read somewhere it could be troublesome-. Last time I upgraded with org files closed and no apparent problem arose. 
Many thanks for your quick response and for org-ref. If there is any other detail concerning this issue that I could  check please let me know.

**Comment by jkitchin** [comment] 2021-11-06 20:02
who knows. I also added a line for compiling that could help too. Glad to hear it is working. I will close this.

**Closed by jkitchin** 2021-11-06 20:02 UTC
