### ISSUE TITLE
org-ref-define-citation-link throws error 'Wrong type argument: consp, nil'

### ISSUE THREAD

**Issue by BenFeld** [jkitchin/org-ref#483] opened 2017-08-08 12:49 UTC
When defining my own citation link `citeshort` the function `org-ref-define-citation-link`throws the error message **Wrong type argument: consp, nil**. The links using this citation link work however.

>  (org-ref-define-citation-link "citeshort" ?z)

**Comment by jkitchin** [comment] 2017-08-08 13:27
Thanks for reporting that. It was caused by there not being an org entry in a reftex variable. I pushed a fix that adds one when there isn't.

**Closed** 2017-08-08 18:47 UTC
