### ISSUE TITLE
Formatted citations with 8+ authors miss the first author

### ISSUE THREAD

**Issue by martinleduc** [jkitchin/org-ref#690] opened 2019-11-22 04:33 UTC
Hi,

When cursor is over a citation link corresponding to an entry that contains 8 or more authors in the bibtex file, the formatted reference preview at the bottom of the screen is missing the first author (Me ! ;) ). Same result if I "Copy formatted entry". It seems there is a special condition for 8+ authors since there the last authors are also replaced with "…" 

I tested with several bibtex references and it seems to be systematic. Here is an example:

@article{leduc19_climex_projec,
  author =	 {Leduc, Martin and Mailhot, Alain and Frigon, Anne
                  and Martel, Jean-Luc and Ludwig, Ralf and Brietzke,
                  Gilbert B. and Gigu{\`e}re, Michel and Brissette,
                  Fran{\c{c}}ois and Turcotte, Richard and Braun,
                  Marco and Scinocca, John},
  title =	 {{The Climex Project: A 50-member Ensemble of Climate
                  Change Projections At 12-km Resolution Over Europe
                  and Northeastern North America With the Canadian
                  Regional Climate Model (CRCM5)}},
  journal =	 {Journal of Applied Meteorology and Climatology},
  volume =	 58,
  number =	 4,
  pages =	 {663-693},
  year =	 2019,
  doi =		 {10.1175/JAMC-D-18-0021.1},
}

Will give :

Mailhot, A., Frigon, A., Martel, J., Ludwig, R., Brietzke, G. B., Gigu\`ere, Michel, Brissette, Fran\ccois, …, The Climex Project: A 50-member Ensemble of Climate Change Projections At 12-km Resolution Over Europe and Northeastern North America With the Canadian Regional Climate Model (CRCM5), Journal of Applied Meteorology and Climatology, 58(4), 663–693 (2019).  http://dx.doi.org/10.1175/JAMC-D-18-0021.1

Rather than:

Leduc, M., Mailhot, A., Frigon, A., Martel, J., Ludwig, R., Brietzke, G. B., Gigu\`ere, Michel, Brissette, Fran\ccois, …, The Climex Project: A 50-member Ensemble of Climate Change Projections At 12-km Resolution Over Europe and Northeastern North America With the Canadian Regional Climate Model (CRCM5), Journal of Applied Meteorology and Climatology, 58(4), 663–693 (2019).  http://dx.doi.org/10.1175/JAMC-D-18-0021.1

Thanks !

**Comment by jkitchin** [comment] 2019-11-25 14:29
I was unable to reproduce this.  That message is created in org-ref-format-bibtex-entry I think, that would be a good place to start. I can't see anything special about 8+ authors though.

**Comment by Ypot** [comment] 2020-01-08 11:04
Here it looks ok:
![Captura2](https://user-images.githubusercontent.com/30699014/71973284-ddc7a100-320e-11ea-807e-32dc11cb143a.JPG)
![Nueva imagen de mapa de bits](https://user-images.githubusercontent.com/30699014/71973335-0354aa80-320f-11ea-91d2-f02d6f36b501.jpg)

**Comment by jkitchin** [comment] 2020-01-08 13:26
There is a formatting code that abbreviates author lists with more than 9 authors. Maybe that abbreviation makes it look like the first author is truncated somehow, although for me it works as expected, and in the example above. Given two examples that look ok, I am going to close this for now.

**Closed by jkitchin** 2020-01-08 13:26 UTC
