### ISSUE TITLE
error when switching to melpa version

### ISSUE THREAD

**Issue by zeltak** [jkitchin/org-ref#82] opened 2015-12-18 07:43 UTC
Hi John

i switched today from the git version to melpa and i get this error on start-up

```
Warning (initialization): An error occurred while loading `/home/zeltak/.emacs.d/init.el':

Wrong number of arguments: #[nil \212\302 \210\303\304 ;\203\305\306	#\202\307A@	"+\207 [element property outline-previous-heading :commentedp org-element-at-point get-text-property 0 plist-get] 4 (/home/zeltak/.emacs.d/elpa/org-ref-20151217.1847/org-ref.elc . 28551)], 1
```
also is the jmax-bibtex included in the melpa package?

best

z

**Comment by brabalan** [comment] 2015-12-18 10:54
I also have a problem with the Melpa version, about a wrong argument `nil` for `keymapp`. I can provide a backtrace if it helps.

**Comment by jkitchin** [comment] 2015-12-18 11:10
jmax-bibtex was renamed to org-ref-bibtex (and all the jmax- functions were renamed to org-ref- functions). I just pushed a fix for an unknown email-bibtex-entry function.

@zeltak If you are using org 8.3 then a recent push this morning may resolve the issue.

@brabalan can you see what the keymapp issue is? Is it with LaTeX-mode-map?

**Comment by brabalan** [comment] 2015-12-18 12:02
It's a problem with helm-bibtex it seems:
``` emacs-lisp
  easy-menu-get-map(nil ("Tools" "Helm" "Tools") nil)
  easy-menu-add-item(nil ("Tools" "Helm" "Tools") ["BibTeX" helm-bibtex t])
  byte-code("…" [require helm helm-net helm-plugin parsebib cl-lib dash s f custom-declare-group helm-bibtex nil "Helm plugin for searching entries in a BibTeX bibliography." :group custom-declare-variable helm-bibtex-bibliography "The BibTeX file or list of BibTeX files." :type (choice file (repeat file)) helm-bibtex-library-path "A directory or list of directories in which PDFs are\nstored.  Helm-bibtex assumes that the names of these PDFs are\ncomposed of the BibTeX-key plus a \".pdf\" suffix." (choice directory (repeat directory)) helm-bibtex-pdf-open-function (quote find-file) "The function used for opening PDF files.  This can be an\narbitrary function that takes one argument: the path to the PDF\nfile.  The default is `find-file' which opens the PDF in\nEmacs (either with docview or, if installed, the much superior\npdf-tools.  When set to `helm-open-file-with-default-tool', the\nsystems default viewer for PDFs is used." function helm-bibtex-pdf-symbol "⌘" "Symbol used to indicate that a PDF file is available for a\npublication.  This should be a single character." string helm-bibtex-format-citation-functions (quote ((org-mode . helm-bibtex-format-citation-ebib) (latex-mode . helm-bibtex-format-citation-cite) (markdown-mode . helm-bibtex-format-citation-pandoc-citeproc) (default . helm-bibtex-format-citation-default))) "The functions used for formatting citations.  The publication\ncan be cited, for example, as cite{key} or ebib:key depending on\nthe major mode of the current buffer.  Note that the functions\nshould accept a list of keys as input.  With multiple marked\nentries one can insert multiple keys at once,\ne.g. cite{key1,key2}. See the functions\n`helm-bibtex-format-citation-ebib' and\n`helm-bibtex-format-citation-cite' as examples." (alist :key-type symbol :value-type function) helm-bibtex-notes-path "The place where notes are stored.  This is either a file, in\nwhich case all notes are stored in that file, or a directory, in\nwhich case each publication gets its own notes file in that\ndirectory.  In the latter case, helm-bibtex assumes that the\nnames of the note files are composed of the BibTeX-key plus a\nsuffix that is specified in `helm-bibtex-notes-extension'." (choice file directory) helm-bibtex-notes-template-multiple-files "#+TITLE: Notes on: ${author} (${year}): ${title}\n\n" "Template used to create a new note when each note is stored in\na separate file.  '${field-name}' can be used to insert the value\nof a BibTeX field into the template." helm-bibtex-notes-template-one-file "\n* ${author} (${year}): ${title}\n  :PROPERTIES:\n  :Custom_ID: ${=key=}\n  :END:\n\n" "Template used to create a new note when all notes are stored\nin one file.  '${field-name}' can be used to insert the value of\na BibTeX field into the template." helm-bibtex-notes-key-pattern ":Custom_ID: +%s\\( \\|$\\)" "The pattern used to find entries in the notes file.  Only\nrelevant when all notes are stored in one file.  The key can be\ninserted into the pattern using the `format` function." helm-bibtex-notes-extension ".org" "The extension of the files containing notes.  This is only\nused when `helm-bibtex-notes-path' is a directory (not a file)." helm-bibtex-notes-symbol ...] 8)
  require(helm-bibtex)
  byte-code("…" [require dash doi-utils helm helm-bibtex helm-config hydra org-ref-bibtex org org-element ox reftex reftex-cite] 2)
  require(org-ref)
```

**Comment by jkitchin** [comment] 2015-12-18 14:18
Thanks for the traceback. I can't reproduce it on my end.

@tmalsburg is this a known issue in helm-bibtex?

**Comment by zeltak** [comment] 2015-12-18 15:13
thx John

new commit on melpa fixes it!

txh

Z

**Comment by tmalsburg** [comment] 2015-12-18 16:48
@brabalan, helm-bibtex is trying to add an entry to a menu that helm hasn't created yet. This suggests that you are loading helm-bibtex before helm.  The other way around should work.

**Comment by dlebrecht** [comment] 2015-12-18 19:29
i have the same issue as @brabalan. git version commit 656cca09bd0ea7aa96a0d1555ba3ed16eadc466b
 worked perfectly, but a few days after this error came up. the issue is in the main branch too.

**Comment by jkitchin** [comment] 2015-12-19 01:24
I still can't reproduce this with a bare bones emacs and a fresh org-ref install.

Something like this in an el file:

(setq user-emacs-directory "./sandbox")
(require 'package)

(setq package-archives
      '(("org" . "http://orgmode.org/elpa/")
	("gnu" . "http://elpa.gnu.org/packages/")
	("melpa" . "http://melpa.org/packages/")))

(package-initialize)
(package-refresh-contents)

(package-install 'org-ref)

(require 'org-ref)


and then running this:

rm -fr sandbox
emacs -Q -l test-new-melpa.el

**Comment by minkkinen** [comment] 2015-12-19 12:30
I had the same issue as @brabalan and @dlebrecht. I was able to solve it by adding (require 'helm-config) before (require 'org-ref) to my .emacs. This line is mentioned in the helm readme, but I had missed it because helm-bibtex and org-ref had previously worked perfectly well without it.

**Comment by jkitchin** [comment] 2015-12-19 12:52
Thanks for figuring that out. It does turn out the requires were recently re-organized, and helm-config was moved after helm and helm-bibtex. I pushed a change to put the order back.

**Comment by brabalan** [comment] 2015-12-21 07:31
I confirm that everything is now working here. Thanks!

**Comment by jkitchin** [comment] 2015-12-21 10:56
Thanks for letting me know!

**Closed by jkitchin** 2015-12-21 10:56 UTC
