### ISSUE TITLE
citation for "misc" type cause error

### ISSUE THREAD

**Issue by xarthurx** [jkitchin/org-ref#380] opened 2017-02-09 02:58 UTC
"Error running timer: 'org-ref-link-message': (wrong-type-argument arrayp nil"

if change "@misc" to other types, it will work fine.

**Comment by jkitchin** [comment] 2017-02-09 07:44
I think this fixed. Thanks for reporting it.

**Comment by NLisa** [comment] 2017-02-21 09:08
This is also true for **"@mscthesis"**. Problem does not manifest for **"@phdthesis"**.

**Comment by jkitchin** [comment] 2017-02-21 13:55
I am pretty sure mscthesis is not a valid bibtex type. It should be @MastersThesis if you are using bibtex.

**Comment by NLisa** [comment] 2017-02-21 18:34
Hi sorry, that was my mistake. Yes you are correct, I was typing on phone and had meant @mastersthesis.

However it is a moot point, as I can confirm both @misc and @mastersthesis now work correctly as of version `org-ref-20170217.1354`.

This issue can probably be closed...?

Regards

**Comment by jkitchin** [comment] 2017-02-21 19:41
It looks like it. The previous versions would give this issue when the type wasn't defined in org-ref. I think it has a default value now to work. I will close it for now. Thanks for using org-ref!

**Closed by jkitchin** 2017-02-21 19:41 UTC
