### ISSUE TITLE
typo in ```org-ref-cite-re```?

### ISSUE THREAD

**Issue by Lompik** [jkitchin/org-ref#593] opened 2018-08-01 11:34 UTC
https://github.com/jkitchin/org-ref/blob/a40f80d59a6ef63c199d9043b4fff30853d62c59/org-ref-core.el#L631

The colon should probably be after the closing escaped paren.
Currently it matches ```citeaaa:doc```

**Comment by jkitchin** [comment] 2018-08-01 12:33
I can't reproduce this issue. The link you suggested is not matched for me. Are you sure you don't have citeaaa in the variable org-ref-cite-types?

**Comment by Lompik** [comment] 2018-08-01 14:21
You're right, it is not a user visible issue because there are additional checks (I have not used this package yet).  

Doesn't ```(string-match org-ref-cite-re "citeaaa:doc")``` returns ```0``` for you ? 
With the change below (marked with "<---"), it would return ```nil```.  Would this not be a preferred behaviour ?
```elisp
(defvar org-ref-cite-re
  (concat "\\(" (mapconcat
                 (lambda (x)
		   (replace-regexp-in-string "\*" "\\\\*" x))
                 org-ref-cite-types "\\|") ":\\)"         <---   "\\):" 
                 "\\([a-zA-Z0-9-_:\\./]+,?\\)+")
  "Regexp for cite links.")```

**Comment by jkitchin** [comment] 2018-08-02 14:55
I see what you mean, that is indeed a typo. I have pushed a fix for it. Thanks for bringing it to my attention.

**Closed** 2018-08-02 15:45 UTC
