### ISSUE TITLE
"copy formatted citation to clipboard" gives `!!! No Entry Found !!!`

### ISSUE THREAD

**Issue by ssfrr** [jkitchin/org-ref#641] opened 2019-03-13 13:36 UTC
It seems that org-ref is successfully finding my bibliography (it shows the right info when point is on the `cite:xxx` link), but when I press enter on the link and choose "Copy formatted citation to clipboard" what gets copied is `!!! No Entry Found !!!`.

other commands like "add notes" and "open PDF" seem to work fine.

Any hints on troubleshooting?

I'm using org version 9.2 and org-ref version 20190118.1502

**Comment by jkitchin** [comment] 2019-03-13 14:38
can you post the bibtex entry that you are trying to use, and the org-file that causes it (just the minimal required to reproduce it).

**Comment by ckelty** [comment] 2019-03-22 18:12
I'm getting the same problem.
Emacs on MacOSX  v26.1, orgmode version 9.1.4, org-ref 20190107.209

Using emacs -Q and loading only org and org-ref
Using this bibliography entry retrieved with org-ref's doi-add-bibtex-entry

@article{dimaggio83_iron_cage_revis,
  author =	 {Paul J. DiMaggio and Walter W. Powell},
  title =	 {The Iron Cage Revisited: Institutional Isomorphism
                  and Collective Rationality in Organizational Fields},
  journal =	 {American Sociological Review},
  volume =	 48,
  number =	 2,
  pages =	 147,
  year =	 1983,
  doi =		 {10.2307/2095101},
  url =		 {https://doi.org/10.2307/2095101},
  DATE_ADDED =	 {Fri Mar 22 11:06:19 2019},
}

cite:dimaggio83_iron_cage_revis

!!! No entry found !!!

**Comment by jkitchin** [comment] 2019-04-07 21:39
This must be happening because the bib file is not getting saved. Can you try this, go to the bib file and save it, and then see if the issue goes away?

**Comment by ckelty** [comment] 2019-04-08 19:39
No, it happens even if the bib file is not open, or if I open it, change it and save it.  
Weirdly, if I look at the *Messages* buffer, the formatted citation is there--- it's just not getting copied to the clipboard/kill-ring?

From *Messages* (after doing C-c ] Dimag<tab> <ret> <click citation> 17 <ret> C-y)

DiMaggio, P. J., & Powell, W. W., The Iron Cage Revisited: Institutional Isomorphism and Collective Rationality in Organizational Fields, American Sociological Review, 48(2), 147–160 (1983).  http://dx.doi.org/10.2307/2095101
Mark set
Error during redisplay: ((lambda (window object position) (when org-ref-show-citation-on-enter (save-excursion (goto-char position) (let ((s (org-ref-format-entry (org-ref-get-bibtex-key-under-cursor)))) (with-temp-buffer (insert s) (fill-paragraph) (buffer-string)))))) #<window 27 on *Messages*> #<buffer todo.org> 765372) signaled (wrong-type-argument stringp nil) [3 times]

**Comment by NickDaly** [comment] 2019-10-20 16:10
I was seeing similar issues where cites could not be found when placing the cursor over valid cites.  The error message led me to `(require 'bibtex-completion)` which resolved it for me.

```
Buffer is syntactically correct
!!! No entry found !!!
Error during redisplay: (jit-lock-function 1) signaled (void-function bibtex-completion-get-entry) [2 times]
```

----

Versions:

- GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-09-22, modified by Debian
- Org mode version 9.2.3 (9.2.3-dist @ /usr/share/emacs/site-lisp/elpa/org-9.2.3/)
- org-ref: Version 1.1.1

**Comment by jkitchin** [comment] 2019-10-20 18:14
I think the wrong function was getting called, one that works on a bibtex entry, not on a link. I think this is fixed now.

I haven't seen the bibtex-completion issue yet, but what you did should fix the issue you were seeing I think.

**Comment by ckelty** [comment] 2019-10-21 18:24
That fixed my issue! Thank you thank you...

**Closed** 2019-10-21 18:37 UTC

**Comment by juanerasmoe** [comment] 2020-07-27 16:01
Similar to this, if you try to copy a formatted citation from the ivy actions menu you get the '!!! No Entry Found !!!' text in your clipboard.

Steps to reproduce:
* `M-x org-ref-ivy-insert-cite-link` 
* Select any entry
* `M-o`
*  `F`

Interestingly, if you chose `f` in the ivy menu (Insert formatted citation), it does work.

**Comment by jkitchin** [comment] 2020-08-08 16:08
Thanks for reporting this. I think I have pushed a fix for it.
