### ISSUE TITLE
Typo in helm-bibtex-candidates-formatter (?)

### ISSUE THREAD

**Issue by hungerartist** [jkitchin/org-ref#22] opened 2015-03-14 19:59 UTC
First, thanks for the awesome package! Second, I don't really know elisp, so what follows might not be "the" problem, but it seems to be "a" problem for me and hopefully it's a clue about what's happening.

I updated org-ref yesterday after not having updated in a couple of weeks, and helm-bibtex stopped working in the sense that after loading my bibtex file, it would display nothing. The entire window was blank, and when I inserted a citation I got 400 blank spaces. After a lot of digging, I think it boils down to "it" and "entry" being in the wrong order for the helm-bibtex-get-value function, where the function helm-bibtex-candidates-formatter is being defined in org-ref. I'm no elisp programmer, but when I checked the doctstring for helm-bibtex-get-value, it looks like "it" should be before "entry." Now helm-bibtex works---it isn't blank---but I'm still getting the org-ref citation 400 spaces long.

**Comment by hungerartist** [comment] 2015-03-14 20:57
ps. 400 characters is the width of my helm-bibtex buffer, so it looks like it's inserting the entire line from helm-bibtex into the org-ref citation. I'm using Org 8.2.10 and Emacs 24.4.

**Comment by jkitchin** [comment] 2015-03-14 22:06
Thanks for mentioning it, and pointing out the problem. It looks like helm-bibtex changed that function since I added this to org-ref. I pushed a fix that seems to fix it for me with the latest helm-bibtex.

I cant reproduce the 400 space long issue though.

**Closed by jkitchin** 2015-03-14 22:06 UTC

**Comment by hungerartist** [comment] 2015-03-15 19:37
Excellent. Thank you. And thanks again for an awesome package.
