### ISSUE TITLE
"M-x org-ref" -> org-ref-list-index: No catch for tag: --cl-block-nil--, 0

### ISSUE THREAD

**Issue by bipsen** [jkitchin/org-ref#813] opened 2020-11-16 20:01 UTC
On a fresh install of Emacs I am unable to get org-ref to produce citations in my pdfs. I simply get question marks and in Org PDF Latex Output I get a lot of `LaTeX Warning: Citation XXX on page XX undefined on input line XX.`

Doing `C-c ]` works fine and so does `M-x org-ref`. However, if I run `M-x org-ref` after inserting a citation somewhere in the document, I get the following error: `org-ref-list-index: No catch for tag: --cl-block-nil--, 0`. So I wonder if that might have something to do with it.

My org file (thesis.org) and bib file (bibliography.bib) are in the same folder. 

Edit: producing just the .tex file and then running pdflatex, then bibtex then two times pdflatex in terminal according to [this answer][1] works. The normal org-ref pdf-making process then works when I already have the bbl file, but I still get the error when running `M-x org-ref` when the .org file already has a citation in it.

 - Org-ref version: 20201013.1427
 - OS: Ubuntu 20.10
 - Emacs version: 26.3

The output of `M-x org-ref` (when it does work) is: (I transcriped this from the screen, so please allow typos)
```
* Bibliography
Using the bibtex files: (bibliography.bib)

* Miscellaneous
org-latex-prefer-user-labels = nil
bibtex-dialect = BibTeX
biblatex is not required.
biblatex is not used.
org-version = 9.4
completion backend = org-ref-helm-bibtex
org-latex-pdf-process is defined as (%latex -interaction nonstopmode -output-directory %o %f %latex -interaction nonstopmode -output-directory %o %f %latex -interaction nonstopmode -output-directory %o %f)
natbib is not required.
natbib is not used.
cleveref is not required.
cleveref is not used.

* Utilities
Check buffer again
```

**thesis.org**
```
* Header

Some text. cite:knuthwebsite

bibliographystyle:unsrt
bibliography:bibliography.bib


```

**bibliography.bib**
```
@article{einstein,
    author =       "Albert Einstein",
    title =        "{Zur Elektrodynamik bewegter K{\"o}rper}. ({German})
        [{On} the electrodynamics of moving bodies]",
    journal =      "Annalen der Physik",
    volume =       "322",
    number =       "10",
    pages =        "891--921",
    year =         "1905",
    DOI =          "http://dx.doi.org/10.1002/andp.19053221004"
}

@book{latexcompanion,
    author    = "Michel Goossens and Frank Mittelbach and Alexander Samarin",
    title     = "The \LaTeX\ Companion",
    year      = "1993",
    publisher = "Addison-Wesley",
    address   = "Reading, Massachusetts"
}

@misc{knuthwebsite,
    author    = "Donald Knuth",
    title     = "Knuth: Computers and Typesetting",
    url       = "http://www-cs-faculty.stanford.edu/\~{}uno/abcde.html"
}
```
**init.el**
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
;; and `package-pinned-packages`. Most users will not need or want to do this.
;;(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(package-initialize)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(inhibit-startup-buffer-menu nil)
 '(inhibit-startup-screen t)
 '(package-selected-packages
   (quote
    (helm-swoop org-superstar org-brain org use-package tidal py-autopep8 org-bullets flycheck elpy))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

;; -------------------------------------------------------------
;; org
(add-hook 'org-mode-hook (lambda () (org-superstar-mode 1)))

;; -------------------------------------------------------------
;; latex
(require 'ox-latex)

(add-to-list 'org-latex-classes
      '("mimosis"
         "\\documentclass{mimosis}
         [NO-DEFAULT-PACKAGES]
         [PACKAGES]
         [EXTRA]"
	 ("\\chapter{%s}" . "\\chapter*{%s}")
	 ("\\section{%s}" . "\\section*{%s}")
	 ("\\subsection{%s}" . "\\subsection*{%s}")
	 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
	 ("\\mboxparagraph{%s}" . "\\mboxparagraph*{%s}")
	 ("\\mboxsubparagraph{%s}" . "\\mboxsubparagraph*{%s}")))

;; -------------------------------------------------------------
;; org-ref
(require 'org-ref)

(setq reftex-default-bibliography '("~/test/bibliography.bib"))

;; see org-ref for use of these variables
(setq org-ref-bibliography-notes "~/test/notes.org"
      org-ref-default-bibliography '("~/test/bibliography.bib")
      org-ref-pdf-directory "~/test/papers")

(setq bibtex-completion-bibliography "~/test/bibliography.bib"
      bibtex-completion-library-path "~/test/papers"
      bibtex-completion-notes-path "~/test/helm-bibtex-notes")

;; -------------------------------------------------------------
;; helm
(require 'helm)

(global-set-key (kbd "C-x C-f") 'helm-find-files)

;; helm-swoop
(require 'helm-swoop)

(global-set-key (kbd "M-i") 'helm-swoop)
(global-set-key (kbd "M-I") 'helm-swoop-back-to-last-point)
(global-set-key (kbd "C-c M-i") 'helm-multi-swoop)
(global-set-key (kbd "C-x M-i") 'helm-multi-swoop-all)
(define-key isearch-mode-map (kbd "M-i") 'helm-swoop-from-isearch)
(define-key helm-swoop-map (kbd "M-i") 'helm-multi-swoop-all-from-helm-swoop)
(setq helm-multi-swoop-edit-save t)
(setq helm-swoop-use-fuzzy-match t)
```

  [1]: https://tex.stackexchange.com/a/354218

**Comment by jkitchin** [comment] 2020-11-25 21:45
This seems strange. I think you are missing a call to bibtex in `org-latex-pdf-process` which is why you don't see citations. But, if it used to work, and you haven't changed that, it doesn't seem likely. See https://github.com/jkitchin/org-ref/blob/master/org-ref.org#latex-export though, just in case.

I have never seen the error you mention at the top though.

**Comment by fleimgruber** [comment] 2020-12-27 07:49
Seeing a similar error, the top of the traceback:

```
Debugger entered--Lisp error: (no-catch --cl-block-nil-- 9)
  throw(--cl-block-nil-- 9)
  org-ref-list-index("ahrensHowTakeSmart2017" ("325BEE" "abbottFlatlandRomanceMany2011" "abelsonStructureInterpretationComputer1996" ...
```

after that follows a long sequence of cite keys and further down a lot of

```
#f(compiled-function (link) #<bytecode 0x1fe241d432d5>)((link (:type "cite" :path "ahrensHowTakeSmart2017" :format plain :raw-link "cite:ahrensHowTakeSmart2017" :application nil :search-option nil :begin 89722 :end 89749 :contents-begin nil :contents-end nil :post-blank 0 :parent (paragraph (:begin 89722 :end 89750 :contents-begin 89722 :contents-end 89750 :post-blank 0 :post-affiliated 89722 :parent (section (:begin 89722 :end 89751 :contents-begin 89722 :contents-end 89750 :post-blank 1 :post-affiliated 89722 :parent (headline ... #43)) #27)) #1 #("\n" 0 1 (:parent #27))))))
  #f(compiled-function (--data) #<bytecode 0x1fe240dad669>)((link (:type "cite" :path "ahrensHowTakeSmart2017" :format plain :raw-link "cite:ahrensHowTakeSmart2017" :application nil :search-option nil :begin 89722 :end 89749 :contents-begin nil :contents-end nil :post-blank 0 :parent (paragraph (:begin 89722 :end 89750 :contents-begin 89722 :contents-end 89750 :post-blank 0 :post-affiliated 89722 :parent (section (:begin 89722 :end 89751 :contents-begin 89722 :contents-end 89750 :post-blank 1 :post-affiliated 89722 :parent (headline ... #43)) #27)) #1 #("\n" 0 1 (:parent #27))))))
  mapc(#f(compiled-function (--data) #<bytecode 0x1fe240dad669>) ((link (:type "cite" :path "ahrensHowTakeSmart2017" :format plain :raw-link "cite:ahrensHowTakeSmart2017" :application nil :search-option nil :begin 89722 :end 89749 :contents-begin nil :contents-end nil :post-blank 0 :parent (paragraph (:begin 89722 :end 89750 :contents-begin 89722 :contents-end 89750 :post-blank 0 :post-affiliated 89722 :parent (section (:begin 89722 :end 89751 :contents-begin 89722 :contents-end 89750 :post-blank 1 :post-affiliated 89722 :parent ...) #29)) . #2))) #("\n" 0 1 (:parent (paragraph (:begin 89722 :end 89750 :contents-begin 89722 :contents-end 89750 :post-blank 0 :post-affiliated 89722 :parent (section (:begin 89722 :end 89751 :contents-begin 89722 :contents-end 89750 :post-blank 1 :post-affiliated 89722 :parent ...) #7)) . #2)))))
```

**Comment by jkitchin** [comment] 2020-12-28 22:38
I am not sure what would be causing this still. I guess the issue is with cl-return for some reason. Can you run this code:

```
(let ((i 0)
      (found nil))
    (dolist (arg '("tree" "test" "frogg") i)
      (if (string-match (concat "^" "test" "$") arg)
          (progn
            (setq found t)
            (cl-return i)))
      (setq i (+ i 1)))
    ;; return counter if found, otherwise return nil
    (if found i nil))
```

**Comment by fleimgruber** [comment] 2020-12-28 23:00
That code evaluates to `1 (#o1, #x1, ?\C-a)`

**Comment by fleimgruber** [comment] 2020-12-28 23:04
Just for additional reference:
org-ref: 1.1.1 (git-commit 97418aaa4f317292b1aee0d4ab5bfceec2f0c03f)
Emacs: 27.1
OS: macOS 10.12.6

**Comment by jkitchin** [comment] 2020-12-28 23:11
huh. I don't seem to have that commit in my history.  how did you install org-ref?

**Comment by fleimgruber** [comment] 2020-12-28 23:20
I pasted the output of `(org-ref-version)` which somehow picks up the git commit from Spacemacs on develop branch. org-ref is installed via the `bibtex` layer there. Ultimately MELPA is used I guess, the version on disk is org-ref-20201126.1924.

**Comment by jkitchin** [comment] 2020-12-29 21:19
> That code evaluates to `1 (#o1, #x1, ?\C-a)`

That is what it should do. I wonder if this is some weird *.elc issue, e.g. left over from an update. You might try removing all the .elc files in your elpa directory, and if that makes the problem go away, you could try recompiling them.

**Comment by fleimgruber** [comment] 2020-12-29 22:01
Thanks for the suggestion, removed the .elc files and the problem went away.

**Comment by jkitchin** [comment] 2020-12-29 22:28
@bipsen I guess that is the issue for you too.

**Comment by fleimgruber** [comment] 2020-12-31 10:20
In 734754f8b836ce834233e8eaae1c40cfc3db8091 there is a new check for the .el vs. .elc issue. After the latest update of org-ref I hit this error again on calling `(org-ref)`. I was just wondering if the check for .el vs. .elc files could happen earlier in the function or at least before `(org-ref-list-index)`, as this is where the error originates, at least for me, see https://github.com/jkitchin/org-ref/issues/813#issuecomment-751437123).

**Comment by jkitchin** [comment] 2020-12-31 14:14
good point. I have moved this check as far up as I can. I think it happens first now.

**Comment by jkitchin** [comment] 2021-01-07 13:26
I believe this issue has been resolved and am closing this issue. If it returns, please reopen or make a new issue.

**Closed** 2021-01-07 13:26 UTC
