### ISSUE TITLE
Produces errors unless tangled manually

### ISSUE THREAD

**Issue by divinenephron** [jkitchin/org-ref#6] opened 2015-02-14 11:03 UTC
`org-ref` has been producing errors if I do not tangle it manually.

**Steps to reproduce**

1. Download a85b032e9f5083ec4d030e56486a7f70c72e0eb1.
2. Add the following to `init.el`
    
    ```emacs-lisp
    (require 'helm-config) ; Needed because of issue #5
    (add-to-list 'load-path "<path to org-ref directory>")
    (org-babel-load-file "<path to org-ref.org>")
    ````
    
3. Run `emacs --debug-init`.
4. Observe the [backtrace][1].
5. Run `org-babel-tangle` on `org-ref.org`.
6. Restart `emacs --debug-init`.
7. Observe no error is produced.
8. Delete `org-ref.el`.
9. Restart `emacs --debug-init`.
10. The same [error][1] is produced again.

[1]: https://gist.github.com/divinenephron/15f582d0db670653717f

**Interpretation**

Somehow the tangling done by `org-babel-load-file` is not including the block where `org-ref-cite-types` is defined, while the tangling done by manually running `org-babel-tangle` is. If you look at the `org-ref.el` generated by `org-babel-load-file` you can verify the definition of `org-ref-cite-types` is absent.

**Workaround**

After I've run `org-babel-tangle` on `org-ref.el`, the program runs fine. I'll have to do this again every time I update `org-ref` however.

**Fix**

I'm not sure how to fix this, but doing so would make new users less confused and make it easier to update `org-ref`.

**Comment by jkitchin** [comment] 2015-02-14 12:01
hm. I cannot reproduce this on master. The way I load org-ref is basically with org-babel-load-file. The only tricky thing I have seen is that you have to do that in the directory where the file is (for some reason) or the org-ref.el file is not always where I expect it. Below is the actual code I use to load it. One of these days I will try to switch this to a straight emacs-lisp file I can edit with lentic maybe.


(defun org-require (feature)
  "Load a FEATURE from an org-file.
FEATURE is a symbol, and it is loaded from an org-file by the name of FEATURE.org, that is in the `org-load-path'.  The FEATURE is loaded from `org-babel-load-file'."
  (let ((org-file (concat (symbol-name feature) ".org"))
	(path))

    ;; find the org-file
    (catch 'result
      (loop for dir in org-load-path do
	    (when (file-exists-p
		   (setq path
			 (expand-file-name
			  org-file
			  dir)))
	      (throw 'result path))))
    (let ((default-directory (file-name-directory path)))
      (org-babel-load-file path))))

;; https://github.com/jkitchin/org-ref
(add-to-list 'org-load-path
	     (expand-file-name "org-ref" starter-kit-dir))

(org-require 'org-ref)

**Comment by divinenephron** [comment] 2015-02-15 11:24
I've created more reproducible examples of the bug in my [org-ref Issue 6 gist][1]. This includes two different elisp files which respectively use `org-babel-load-file` and `org-require`. Both produce similar errors, and these errors are fixed after doing `C-x C-f path/to/org-ref.org RET M-x org-babel-tangle`. Can you reproduce the bug now?

[1]: https://gist.github.com/divinenephron/69538bbd65fbfc13cd33

**Versions**
- GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)
- Org-mode version 8.2.10
- Cask 0.7.2
- org-ref a293ab5b16bffc69aef20fc708ac687e53f6ae59

**Comment by jkitchin** [comment] 2015-02-15 12:32
I think I found the issue. One code block without a tangle argument.  I thought that would not tangle out, but it seems to tangle out of order.  It is an experimental section to change the color of the cite links. I have pushed a fix that I think works.

**Comment by divinenephron** [comment] 2015-02-16 19:49
Thanks, `org-require` now works with HEAD (471e52526e14ad47b0c663fde5799c855703af34).

**Closed** 2015-02-16 19:49 UTC
