### ISSUE TITLE
After recent update, helm-bibtex became orphan package in spacemacs

### ISSUE THREAD

**Issue by et2010** [jkitchin/org-ref#218] opened 2016-05-10 13:00 UTC
And spacemacs will delete orphan packages at startup. When `org-ref` is loaded, `helm-bibtex` will come back again. I can fix this by adding `helm-bibtex` to `dotspacemacs-addtional-packages`, but it's ugly. Any suggestions?

**Comment by ericdanan** [comment] 2016-05-11 10:06
I don't use spacemacs. I have emacs 24.5 but I've read [here](http://endlessparentheses.com/new-in-package-el-in-emacs-25-1-better-dependency-management.html) that emacs 25.1 introduces a `package-autoremove` command that perhaps behaves similarly.

If it is problematic that `org-ref` installs packages it doesn't list as dependencies, and if it is also problematic that `org-ref` lets the user in charge of installing a completion library, then the only solution I can think of is to create separate packages for the different completion libraries. That is, all files could stay in the same repo, but simply define several MELPA:
- package `org-ref-helm-bibtex` would include files `org-ref-helm.el` and `org-ref-helm-bibtex.el` and have `helm-bibtex` as dependency
- package `org-ref-helm-cite` would include files `org-ref-helm.el` and `org-ref-helm-cite.el` and have `helm` as dependency

**Comment by yanok** [comment] 2016-05-12 09:45
I think my issue is somehow related to this, so I don't create a new bug report. I'm also using spacemacs, but I'm completely ok with having `helm-bibtex` among the `additional-packages`. My problem is that `org-ref` doesn't start at all, with the following error message:
```
org-ref: Symbol's function definition is void: org-ref-bad-cite-candidates
```

If I try to load `org-ref` by hand from the IELM prompt I get another error:
```
ELISP> (require 'org-ref)
*** Eval error ***  Symbol's value as variable is void: bibtex-completion-format-citation-functions
```

And only if I load `bibtex-completion` by hand before trying to load `org-ref` it starts to work somehow, though the list of possible citations I get by pressing `C-c ]` is still empty (only contains fallback options).

**Comment by jkitchin** [comment] 2016-05-12 20:51
I think you may need to update helm-bibtex. The missing symbol may be in version 2.0, or the latest MELPA version.

**Comment by yanok** [comment] 2016-05-12 23:49
@jkitchin it helped: now I don't have to load `bibtex-completion` by hand and get my bib file entries on `C-c ]`. But I still have to load `org-ref` by hand, just running `org-ref` command results in the same error.

**Comment by hemcsec** [comment] 2016-05-16 03:19
Same here https://github.com/syl20bnr/spacemacs/issues/6014

**Comment by syl20bnr** [comment] 2016-05-20 00:47
> I've read here that emacs 25.1 introduces a package-autoremove command that perhaps behaves similarly.

Indeed it should think that the dependency is orphan as well and remove it.

One possible way to fix this is to break the package into multiple packages; like `org-ref-helm` and make it depend on `org-ref` and `helm-bibtex` etc. This way `packages.el` knows about the dependency and does not have a partial idea of what packages use what so it can make the right decision.

Another way is to implement a new metadata for packages like @abo-abo suggested, something like `Optional-Packages`.

Spacemacs will probably removes its own support for orphan packages and move to `package-autoremove` at some point (we try to rely as much as possible on `package.el`).

cc @malabarba

**Comment by syl20bnr** [comment] 2016-05-20 00:59
Actually `package-autoremove` may not remove the package since it may be considered a top level package installed by `package-install`. @malabarba will be able to confirm or not.

**Comment by syl20bnr** [comment] 2016-05-20 01:05
> One possible way to fix this is to break the package into multiple packages

Mmmmmhhh I think this is the only clean way to do it because, say you can tell `package.el` that `bibtex-helm` is a top-level package when `org-ref` install it automatically, then what happen at uninstall time ? `bibtext-helm` will be seen as a top level package and it won't be autoremove. This defeats the purpose of having `org-ref` "smartly" install `bibtex-helm` for the user.

**Comment by Malabarba** [comment] 2016-05-20 01:34
> Actually package-autoremove may not remove the package since it may be considered a top level package installed by package-install. @malabarba will be able to confirm

That depends on how it's installed. If the user installs a package manually, it is marked as "user-selected" (that is, a top-level package). If the package is installed programmatically (which seems to be the case here) then it is also considered user-selected unless you provide a second argument to `package-install`. 
It was designed this way for backwards compatibility. Fortunately, it means that packages like this will not be installing orphan dependencies. Unfortunately, it means that the newly installed package will be considered user-selected, instead of being considered a proper dependency.

**Comment by Malabarba** [comment] 2016-05-20 01:36
There has been mention of supporting alternate dependencies in package.el. If you think that would help you, it may be good to bring that up on the bug tracker.

**Comment by jkitchin** [comment] 2016-05-20 01:45
I am not crazy about multiple packages, but if they all are served from one git repo, it might not be a big deal. I will give it some thought. There seems to be interest. There would be at least 3 packages:
org-ref+helm-bibtex
org-ref+helm (this is what I use regularly)
org-ref+ivy
there is also technically an option for org-ref+reftex.

 I am traveling for a few days, and will be back next week.

**Comment by Malabarba** [comment] 2016-05-20 14:11
Another, simpler, option is to not install these packages programmatically. Instead, just tell the user 

> Org ref depends on one of these 3 packages: ... 
> Please install one of them from the package menu

**Comment by jkitchin** [comment] 2016-06-10 23:42
It has taken me a while to get think about this ;) I think we could solve this by just making a new org-ref-ivy package for MELPA. We just need an org-ref-ivy.el file with the dependencies that loads what is needed, and a new MELPA recipe that sets it up right? I think this can all be done from the org-ref git repo.

This way we can leave org-ref alone, and provide a helm-free version too. thoughts?

**Comment by syl20bnr** [comment] 2016-06-10 23:49
:+1:

-syl20bnr-

**Comment by ericdanan** [comment] 2016-06-12 13:45
Yes it is possible to manage multiple MELPA packages from the same github repo. I am not an expert but I know two repos that do it:
- `abo-abo/swiper` contains four packages: `ivy`, `ivy-hydra`, `swiper`, `counsel`. For each one, the corresponding `.el` file (`ivy.el`...) contains the relevant `Package-Requires` declaration, and there is a separate MELPA recipe listing which files from the repo are part of the package.
- `emacs-helm/helm` contains two packages: `helm` and `helm-core`. For each one there is a separate `-pkg.el` file (`helm-pkg.el`...) containing only a `define-package` call listing the relevant dependencies. And again there are separate MELPA recipes listing the relevant files.

Both methods apparently work, I don't if one is better than the other.

@jkitchin if I understand correctly you want to revert pull requests #211 and #213 , which caused the current issue as well as #231 , and instead have for instance a file `org-ref-pkg.el` requiring `helm` and another one `org-ref-ivy-pkg.el` requiring `ivy` instead. Am I correct?

**Comment by jkitchin** [comment] 2016-06-12 17:52
I think we can just make a new MELPA package called org-ref-ivy. The
recipe will just exclude the helm files, and include org-ref-ivy.el
which will have the requires in it.

I guess it could be best to revert the commits, but I am also ok with
just deleting the code and putting back in anything needed in a new commit.

ericdanan writes:

> Yes it is possible to manage multiple MELPA packages from the same github repo. I am not an expert but I know two repos that do it:
> - `abo-abo/swiper` contains four packages: `ivy`, `ivy-hydra`, `swiper`, `counsel`. For each one, the corresponding `.el` file (`ivy.el`...) contains the relevant `Package-Requires` declaration, and there is a separate MELPA recipe listing which files from the repo are part of the package.
> - `emacs-helm/helm` contains two packages: `helm` and `helm-core`. For each one there is a separate `-pkg.el` file (`helm-pkg.el`...) containing only a `define-package` call listing the relevant dependencies. And again there are separate MELPA recipes listing the relevant files.
>
> Both methods apparently work, I don't if one is better than the other.
>
> @jkitchin if I understand correctly you want to revert pull requests #211 and #213 , which caused the current issue as well as #231 , and instead have for instance a file `org-ref-pkg.el` requiring `helm` and another one `org-ref-ivy-pkg.el` requiring `ivy` instead. Am I correct?
>
>
>
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/218#issuecomment-225435711


-- 
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by ericdanan** [comment] 2016-06-12 18:22
I see, sounds good to me but there is one thing I don't understand. It seems to me that reverting the commits or deleting / putting back everything implies that `org-ref.el` will again list `helm` as dependency. And also that the new `org-ref-ivy.el` will need to require `org-ref.el`. Won't this make `org-ref-ivy.el` depend on `helm`?

Another question. Couldn't there be a problem if some package wants to depend on `org-ref` "generally" (that is, no matter whether it is the `helm` or `ivy` variant)? (A possible solution could be to have an `org-ref-core` package containing only the file common to all variants, and which all variants)

**Comment by jkitchin** [comment] 2016-06-12 18:29
We will set it up so that:

1. org-ref depends on helm (helm, helm-bibtex, and the org-ref-helm
interface)
2. org-ref-ivy does not depend on helm

so it won't quite be just reverting the commits, but also making it so we
get 1 and 2.

I did think of having a third core, which might just support reftex. I am
not sure it is necessary right now.


John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by ericdanan** [comment] 2016-06-12 18:44
OK thanks for the explanation. Please let me know if I can help with
anything.

**Comment by jkitchin** [comment] 2016-06-14 01:27
I made a branch to try reverting these.

https://github.com/jkitchin/org-ref/tree/ivy-split

My thinking is this
https://github.com/jkitchin/org-ref/blob/ivy-split/org-ref-ivy.el will
define the new org-ref-ivy package. 

I am not sure what to use for the ivy-bibtex version. Right now it is
(ivy-bibtex "2.0.0").

Could you take a look? if it looks ok, we can get a pull request in to
MELPA for org-ref-ivy maybe tomorrow.


ericdanan writes:

> OK thanks for the explanation. Please let me know if I can help with
> anything.
>
> On Sun, Jun 12, 2016 at 8:29 PM, John Kitchin <notifications@github.com>
> wrote:
>
>> We will set it up so that:
>>
>> 1. org-ref depends on helm (helm, helm-bibtex, and the org-ref-helm
>> interface)
>> 2. org-ref-ivy does not depend on helm
>>
>> so it won't quite be just reverting the commits, but also making it so we
>> get 1 and 2.
>>
>> I did think of having a third core, which might just support reftex. I am
>> not sure it is necessary right now.
>>
>>
>> John
>>
>> -----------------------------------
>> Professor John Kitchin
>> Doherty Hall A207F
>> Department of Chemical Engineering
>> Carnegie Mellon University
>> Pittsburgh, PA 15213
>> 412-268-7803
>> @johnkitchin
>> http://kitchingroup.cheme.cmu.edu
>>
>>
>> On Sun, Jun 12, 2016 at 2:22 PM, ericdanan <notifications@github.com>
>> wrote:
>>
>> > I see, sounds good to me but there is one thing I don't understand. It
>> > seems to me that reverting the commits or deleting / putting back
>> > everything implies that org-ref.el will again list helm as dependency.
>> > And also that the new org-ref-ivy.el will need to require org-ref.el.
>> > Won't this make org-ref-ivy.el depend on helm?
>> >
>> > Another question. Couldn't there be a problem if some package wants to
>> > depend on org-ref "generally" (that is, no matter whether it is the helm
>> > or ivy variant)? (A possible solution could be to have an org-ref-core
>> > package containing only the file common to all variants, and which all
>> > variants)
>> >
>> > —
>> > You are receiving this because you were mentioned.
>> > Reply to this email directly, view it on GitHub
>> > <https://github.com/jkitchin/org-ref/issues/218#issuecomment-225452193>,
>> > or mute the thread
>> > <
>> https://github.com/notifications/unsubscribe/ABiRVvpx6XsonWrXWSSatCBiXNN5bRlxks5qLE5UgaJpZM4IbEaG
>> >
>> > .
>>
>> >
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/jkitchin/org-ref/issues/218#issuecomment-225452506>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ALEs2bMOkiCuEcOPfVFPyTf5oTWdgLgpks5qLFABgaJpZM4IbEaG>
>> .
>>
>
>
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/218#issuecomment-225453291


-- 
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by ericdanan** [comment] 2016-06-14 22:12
It looks ok to me. But why is the `ivy-bibtex` dependency needed? I use `org-ref-ivy-bibtex.el` without `ivy-bibtex` and it works well.

**Comment by ericdanan** [comment] 2016-06-15 07:54
Perhaps there is a more flexible solution without more complexity (I suppose you don't want to create many different packages for `ivy-bibtex`, `ivy` without `ivy-bibtex`, and so on): instead of creating an additional package specific to `ivy`, create one that just does not depend on any backend (so the user is in charge of installing `ivy` and/or `helm` and so on).

Unless I am wrong, this can be done simply by creating, instead of the file `org-ref-ivy.el`, a file named `org-ref-core-pkg.el` (or replace "core" with "bare" or any better term), containing only the following code (adapted from `helm-core-pkg.el`):

```
;;; org-ref-core-pkg.el --- define org-ref-core for package.el

(define-package "org-ref-core" "0.8.1"
  "org-ref without dependency on a particular backend"
  '((dash "2.11.0") (hydra "0.13.2") (key-chord "0") (s "1.10.0") (f "0.18.0") (emacs "24.4"))
  :url "https://github.com/jkitchin/org-ref")

;; Local Variables:
;; no-byte-compile: t
;; End:
```

Then no matter which package is installed (`org-ref` or `org-ref-core`), it is loaded with `(require 'org-ref)`.

I don't know if it would then be necessary or desirable to do similarly for the starndard `org-ref` package. That is, remove the `Package-Requires` line from `org-ref.el` and instead create a file `org-ref-pkg.el` containing:

```
;;; org-ref-pkg.el --- define org-ref for package.el

(define-package "org-ref" "0.8.1"
  "citations, cross-references and bibliographies in org-mode"
  '((helm "1.5.5") (helm-bibtex "2.0.0") (dash "2.11.0") (hydra "0.13.2") (key-chord "0") (s "1.10.0") (f "0.18.0") (emacs "24.4"))
  :url "https://github.com/jkitchin/org-ref")

;; Local Variables:
;; no-byte-compile: t
;; End:
```

I hope this make sense. What do you think?

**Comment by jkitchin** [comment] 2016-06-15 09:59
you are right. it is not needed. 

ericdanan writes:

> It looks ok to me. But why is the `ivy-bibtex` dependency needed? I use `org-ref-ivy-bibtex.el` without `ivy-bibtex` and it works well.
>
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/218#issuecomment-226032069


-- 
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jkitchin** [comment] 2016-06-15 11:33
It probably doesn't matter to have three packages, but so far there is
really just requests for the helm free version. anyone who wants less than
that might be ok with the ivy package. There isn't anything stopping
someone from using ivy-bibtex separately and configuring org-ref for it,
so that is probably ok.

I submitted a pull request to MELPA for org-ref-ivy.

BTW I changed the name of org-ref-ivy-bibtex to org-ref-ivy-cite to be
consistent with org-ref-helm-cite, and to avoid confusion with
ivy-bibtex.


ericdanan writes:

> Perhaps there is a more flexible solution without more complexity (I suppose you don't want to create many different packages for `ivy-bibtex`, `ivy` without `ivy-bibtex`, and so on): instead of creating an additional package specific to `ivy`, create one that just does not depend on any backend (so the user is in charge of installing `ivy` and/or `helm` and so on).
>
> Unless I am wrong, this can be done simply by creating, instead of the file `org-ref-ivy.el`, a file named `org-ref-core-pkg.el` (or replace "core" with "bare" or any better term), containing only the following code (adapted from `helm-core-pkg.el`):
>
> ```
> ;;; org-ref-core-pkg.el --- define org-ref-core for package.el
>
> (define-package "org-ref-core" "0.8.1"
>   "org-ref without dependency on a particular backend"
>   '((dash "2.11.0") (hydra "0.13.2") (key-chord "0") (s "1.10.0") (f "0.18.0") (emacs "24.4"))
>   :url "https://github.com/jkitchin/org-ref")
>
> ;; Local Variables:
> ;; no-byte-compile: t
> ;; End:
> ```
>
> Then no matter which package is installed (`org-ref` or `org-ref-core`), it is loaded with `(require 'org-ref)`.
>
> I don't know if it would then be necessary or desirable to do similarly for the starndard `org-ref` package. That is, remove the `Package-Requires` line from `org-ref.el` and instead create a file `org-ref-pkg.el` containing:
>
> ```
> ;;; org-ref-pkg.el --- define org-ref for package.el
>
> (define-package "org-ref" "0.8.1"
>   "citations, cross-references and bibliographies in org-mode"
>   '((helm "1.5.5") (helm-bibtex "2.0.0") (dash "2.11.0") (hydra "0.13.2") (key-chord "0") (s "1.10.0") (f "0.18.0") (emacs "24.4"))
>   :url "https://github.com/jkitchin/org-ref")
>
> ;; Local Variables:
> ;; no-byte-compile: t
> ;; End:
> ```
>
> I hope this make sense. What do you think?
>
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/218#issuecomment-226114533


-- 
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by ericdanan** [comment] 2016-06-15 12:18
OK, I think you also need to rename the file `org-ref-ivy-bibtex.el` to `org-ref-ivy-cite.el`.

**Comment by jkitchin** [comment] 2016-06-15 12:38
Thanks. I pushed that fix too.

**Comment by ericdanan** [comment] 2016-06-15 13:05
It now works for me when I clone the repo and set `org-ref-completion-library` to `org-ref-ivy-cite`, so it seems that everything is renamed properly. I will test the new MELPA package when it is available.

I wonder, what is the purpose of putting `(require 'org-ref-ivy-cite)` in `org-ref-ivy.el`? It seems to me that the goal of the file `org-ref-ivy.el` is only to set the dependencies, and the package should still be loaded with `(require 'org-ref)` so that `org-ref-ivy.el` is never actually loaded. If I try `(require 'org-ref-ivy)` instead, I get an error

```
Symbol's value as variable is void: org-ref-insert-cite-key
```

because `org-ref.el` is not loaded. Am I missing something?

**Comment by jkitchin** [comment] 2016-06-15 13:54
nope, I think you are right. I removed that and put some commentary in. I
think I got it right this time.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jkitchin** [comment] 2016-07-01 13:48
We tried for a couple of weeks to separate out an org-ref-ivy, but it did not succeed. I am tabling this effort and staying with one MELPA package for now. If helm is a deal breaker, I would suggest you run org-ref off the git repo and manage the packages yourself. You could use el-get for that.

**Closed by jkitchin** 2016-07-01 13:48 UTC

**Comment by bdarcus** [comment] 2016-09-25 14:54
Hopefully at some point you can come back to this.

**Comment by jkitchin** [comment] 2016-09-25 17:20
I don't have plans to come back to this. Maybe in some future org-ref-2 it might be designed this way from the beginning, but it doesn't look feasible through MELPA right now.
