### ISSUE TITLE
org-open-at-point fails with wrong-type-argument

### ISSUE THREAD

**Issue by divinenephron** [jkitchin/org-ref#7] opened 2015-02-17 18:04 UTC
When I try to click on a link, or <kbd>C-c</kbd> <kbd>C-o</kbd> it fails with a `wrong-type-argument stringp nil` error.

**Steps to reproduce**

```shell
git clone https://gist.github.com/32b29f1a75bd103e7037.git org-ref-issue-7
cd org-ref-issue-7
emacs -Q -l init.el
# C-x C-f test.org RET
# TAB
# C-n
# C-n
# C-c C-o
```

**Result**

The backtrace is included in [backtrace.txt in the gist][1].

[1]: https://gist.github.com/divinenephron/32b29f1a75bd103e7037#file-backtrace-txt

**Expected result**

Clicking the link and `org-open-at-point` do not produce an error. Instead helm pops up offering some options for doing stuff with the link.

**Speculation**

I looked at the issue with `edebug`. I think the problem is in `org-ref-get-citation-string-at-point`. The call to `bibtex-search-entry` fails to find the entry. When I looked in `bibtex-search-entry` it appears to fail because the variable `bibtex-entry-types` is `nil` when it should be a regex of valid bibtex types (e.g. `@Article{}`). This is because the variable is set when `bibtex-mode` is activated, and the current buffer when `bibtex-search-entry` is called is a temporary buffer in `fundamental-mode`. I'm not sure how to fix this though.

**Comment by jkitchin** [comment] 2015-02-19 14:50
I can't reproduce this error.  Your example works fine for me. It is a better practice to make an explicit bibliography link for a file like this in the org-file than to add it to default bibliographies.

bibliography:test.bib

**Comment by icymist** [comment] 2015-02-19 22:04
I noticed the same error when I am:
- working in an emacs org-mode buffer
- update the underlying default bib file with a new entry
- try to refer to the new entry in the buffer

The error disappears when I restart emacs.

**Comment by jkitchin** [comment] 2015-02-20 01:03
I can reproduce this. I find if you close the bib file, then it works. I
am looking into a way to avoid that.

Chaitanya Krishna Ande writes:

> I noticed the same error when I am:
> - working in an emacs org-mode buffer
> - update the underlying default bib file with a new entry
> - try to refer to the new entry in the buffer
>
> The error disappears when I restart emacs.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/7#issuecomment-75148151

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jkitchin** [comment] 2015-02-20 02:08
I think I have pushed a potential fix for this. Let me know if it
works. Hopefully there is no new issue ;)

Chaitanya Krishna Ande writes:

> I noticed the same error when I am:
> - working in an emacs org-mode buffer
> - update the underlying default bib file with a new entry
> - try to refer to the new entry in the buffer
>
> The error disappears when I restart emacs.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/7#issuecomment-75148151

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Closed** 2015-02-20 19:14 UTC

**Comment by divinenephron** [comment] 2015-02-23 18:29
Neither updating to the latest commit (21e4c9b5f63623a9bcded19d7b1e3e0562cd4174) nor adding `[[bibliography:test.bib]]` to `test.org` resolve my issue. Some time in the future I'll post the exact version of Emacs and the library dependencies I'm using, and try this out using the development versions (perhaps John's works because he's using the development version?).

**Comment by jkitchin** [comment] 2015-02-23 19:00
hmm.. It works for me with a clean emacs and clean clone of org-ref.

I make this my init.el file, with org-ref cloned in the same directory
as the init.el file, the test.bib and test.org file.

Then I run
emacs -Q -l init.el test.org

and it works. The hydra requirement is new.


;; Locations you may have to change
(setq org-ref-path (expand-file-name "org-ref"))

;; Load org-ref
(add-to-list 'load-path org-ref-path)
(add-to-list 'load-path "~/Dropbox/kitchingroup/jmax/elpa/dash-20141201.2206")
(add-to-list 'load-path "~/Dropbox/kitchingroup/jmax/elpa/helm-20150118.1237")
(add-to-list 'load-path "~/Dropbox/kitchingroup/jmax/elpa/helm-bibtex-20141116.2228")
(add-to-list 'load-path "~/Dropbox/kitchingroup/jmax/elpa/ebib-20141203.48")
(add-to-list 'load-path "~/Dropbox/kitchingroup/jmax/elpa/s-20140910.334")
(add-to-list 'load-path "~/Dropbox/kitchingroup/jmax/elpa/f-20140828.716")
(add-to-list 'load-path "~/Dropbox/kitchingroup/jmax/elpa/hydra-20150221.844")

(let ((default-directory org-ref-path))
      (org-babel-load-file (expand-file-name "org-ref.org" org-ref-path)))

(add-to-list 'org-ref-default-bibliography (expand-file-name "./test.bib"))



Devon Buchanan writes:

> Neither updating to the latest commit (21e4c9b5f63623a9bcded19d7b1e3e0562cd4174) nor adding `[[bibliography:test.bib]]` to `test.org` resolve my issue. Some time in the future I'll post the exact version of Emacs and the library dependencies I'm using, and try this out using the development versions (perhaps John's works because he's using the development version?).
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/7#issuecomment-75601451

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by divinenephron** [comment] 2015-02-27 11:01
I tested the following `init.el` with emacs 24.4.1 and 24.4.90.1, and both reproduced the error. It's not an emacs version thing. :disappointed:

```emacs-lisp
(setq org-ref-path (expand-file-name
			 "lisp/org-ref"
			 user-emacs-directory))

;; Load packages
(add-to-list 'load-path org-ref-path)
(add-to-list 'load-path (expand-file-name
			 ".cask/24.4.90.1/elpa/dash-20141220.1452"
			 user-emacs-directory))
(add-to-list 'load-path (expand-file-name
			 ".cask/24.4.90.1/elpa/helm-20150227.152"
			 user-emacs-directory))
(add-to-list 'load-path (expand-file-name
			 ".cask/24.4.90.1/elpa/helm-bibtex-20150223.1004"
			 user-emacs-directory))
(add-to-list 'load-path (expand-file-name
			 ".cask/24.4.90.1/elpa/s-20140910.334"
			 user-emacs-directory))
(add-to-list 'load-path (expand-file-name
			 ".cask/24.4.90.1/elpa/f-20150217.328"
			 user-emacs-directory))
(add-to-list 'load-path (expand-file-name
			 ".cask/24.4.90.1/elpa/hydra-20150226.743"
			 user-emacs-directory))
(add-to-list 'load-path (expand-file-name
			 ".cask/24.4.90.1/elpa/ebib-20150215.257"
			 user-emacs-directory))
(add-to-list 'load-path (expand-file-name
			 ".cask/24.4.90.1/elpa/parsebib-20150205.1305"
			 user-emacs-directory))

;; Load org-ref
(let ((default-directory org-ref-path))
  (org-babel-load-file (expand-file-name "org-ref.org" org-ref-path))
  (org-babel-load-file (expand-file-name "doi-utils.org" org-ref-path))
  (org-babel-load-file (expand-file-name "pubmed.org" org-ref-path)))
(require 'jmax-bibtex)

(add-to-list 'org-ref-default-bibliography (expand-file-name "./test.bib"))
```

To test:

```shell
# First download an emacs build from http://emacsformacosx.com/builds
export EMACS ~/Downloads/Emacs.app/Contents/MacOS/Emacs
git clone https://gist.github.com/32b29f1a75bd103e7037.git org-ref-issue-7
cd org-ref-issue-7
$EMACS -Q -l init.el test.org
# TAB
# C-n
# C-n
# C-c C-o
```

**Comment by jkitchin** [comment] 2015-02-27 13:55
how current is your org-ref?

**Comment by divinenephron** [comment] 2015-02-27 13:57
Super current - 5daa3edea34cadf60484be3d8c613275b3edbb9b

**Comment by jkitchin** [comment] 2015-02-27 14:26
You may have to do some debugging on your end. I cannot reproduce this error. I am using a homebrew emacs, but I find it hard to believe that is the issue.

**Comment by divinenephron** [comment] 2015-02-27 14:33
Yeah, I'll debug it on my end.

**Comment by jkitchin** [comment] 2015-02-27 14:56
I think the default function that is run when you click on a link is: org-ref-cite-click-helm
You might try redefining this to figure out what is going wrong:

e.g.
(defun org-ref-cite-click-helm (key)
  (message "intercepted"))

then start adding to the body to see what is breaking.


You could also try the old function: 
org-ref-cite-onclick-minibuffer-menu
If you like `hydra', consider using `org-ref-cite-hydra'
