### ISSUE TITLE
Received error when calling doi-utils-get-bibtex-entry-pdf on this bibtex

### ISSUE THREAD

**Issue by zhongnanxu** [jkitchin/org-ref#175] opened 2016-04-08 16:55 UTC
error in process sentinel: byte-code: Invalid date: 31-Dec-9999 23:59:59.00 GMT
error in process sentinel: Invalid date: 31-Dec-9999 23:59:59.00 GMT

@article{kunkel-2016-trans-metal,
  author =	 {Christian Kunkel and Francesc Vi{\~n}es and Francesc
                  Illas},
  title =	 {Transition Metal Carbides As Novel Materials for Co
                  2 Capture, Storage, and Activation},
  journal =	 {Energy Environ. Sci.},
  volume =	 9,
  number =	 1,
  pages =	 {141-144},
  year =	 2016,
  doi =		 {10.1039/c5ee03649f},
  url =		 {http://dx.doi.org/10.1039/c5ee03649f},
  abstract =	 "The capture and activation of the greenhouse gas
                  carbon dioxide (CO2) is a prerequisite to its
                  catalytic reforming or breakdown.  Here we report,
                  by means of density functional theory calculations
                  including dispersive forces, that transition metal
                  carbides (TMC; TM = Ti, Zr, Hf, Nb, Ta, Mo) are able
                  to uptake and activate CO2 on their most-stable
                  (001) surfaces with considerable adsorption
                  strength. Estimations of adsorption and desorption
                  rates predict a capture of CO2 at ambient
                  temperature and even low partial pressures,
                  suggesting TMCs as potential materials for CO2
                  abatement.",
  issn =	 "1754-5692",
  keywords =	 "Catalysis: Adsorption/Carbide Adsorption",
  publisher =	 "The Royal Society of Chemistry",
}

Thanks

**Comment by jkitchin** [comment] 2016-04-08 18:39
this seems to be an error pretty deep in Emacs that I have seen before.
Oddly, I couldn't reproduce it. Maybe it is fixed in Emacs25.

It is obviously a ludicrous date ;) I am not sure how to handle it.

Zhongnan Xu writes:

> error in process sentinel: byte-code: Invalid date: 31-Dec-9999 23:59:59.00 GMT
> error in process sentinel: Invalid date: 31-Dec-9999 23:59:59.00 GMT
>
> @article{kunkel-2016-trans-metal,
>   author =     {Christian Kunkel and Francesc Vi{\~n}es and Francesc
>                   Illas},
>   title =      {Transition Metal Carbides As Novel Materials for Co
>                   2 Capture, Storage, and Activation},
>   journal =    {Energy Environ. Sci.},
>   volume =     9,
>   number =     1,
>   pages =      {141-144},
>   year =       2016,
>   doi =                {10.1039/c5ee03649f},
>   url =                {http://dx.doi.org/10.1039/c5ee03649f},
>   abstract =   "The capture and activation of the greenhouse gas
>                   carbon dioxide (CO2) is a prerequisite to its
>                   catalytic reforming or breakdown.  Here we report,
>                   by means of density functional theory calculations
>                   including dispersive forces, that transition metal
>                   carbides (TMC; TM = Ti, Zr, Hf, Nb, Ta, Mo) are able
>                   to uptake and activate CO2 on their most-stable
>                   (001) surfaces with considerable adsorption
>                   strength. Estimations of adsorption and desorption
>                   rates predict a capture of CO2 at ambient
>                   temperature and even low partial pressures,
>                   suggesting TMCs as potential materials for CO2
>                   abatement.",
>   issn =       "1754-5692",
>   keywords =   "Catalysis: Adsorption/Carbide Adsorption",
>   publisher =  "The Royal Society of Chemistry",
> }
>
> Thanks
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/175


--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Closed** 2016-04-08 19:44 UTC
